version: '3'

networks:
  symfony:

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - symfony
  php:
    build:
      context: .
      dockerfile: ./build/php/Dockerfile
    restart: on-failure
    environment:
      PHP_IDE_CONFIG: serverName=docker-server
    volumes:
      - ./app:/var/www/symfony
    networks:
      - symfony
  nginx:
    build:
      context: .
      dockerfile: ./build/nginx/Dockerfile
    restart: on-failure
    volumes:
      - ./app:/var/www/symfony
    ports:
      - ${NGINX_PORT}:80
    networks:
      - symfony
    depends_on:
      - db
      - php